<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>💬 Bate Papo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <link rel="stylesheet" href="app/public/css/chat/online-list.css">
    <link rel="stylesheet" href="app/public/css/chat/message.css">
    <link rel="stylesheet" href="app/public/css/chat/main.css">
    <link rel="stylesheet" href="app/public/css/animated.css">
    <link rel="stylesheet" href="app/public/css/layout.css">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>
  <body>
    <div class="box-group">
      <section class="online-list">
        <header class="online-list-header">
          <div class="bg-success-subtle border border-success-subtle rounded-2 p-1 d-flex align-items-center">
            <div class="online-circle mx-2"></div> <span id='numberOfUsers' class='online-count'><i class="fa fa-refresh fa-spin"></i> Online</span>
          </div>
        </header>
        <div class='users-list' id="users-list"></div>
      </section>
      <section class="chat-content">
        <header class="chat-box-header">

          <div class="header-button notify" onclick="console.log('notify')">
            <i class="fa fa-bell"></i>
          </div>

          <div class="user-name-tag">
            <p style="margin:0;"><?= isset($_SESSION['user_name']) ? $_SESSION['user_name'] : '...' ?><i class="fa fa-user" style="margin-left:5px;"></i></p>
          </div>

          <div class="header-button change-theme" onclick="changeTheme()">
            <i class="fa fa-moon"></i>
          </div>

          <div class="header-button logout" onclick="logout()">
            <i class="fa fa-arrow-left"></i>
          </div>
        </header>
        <main class="chat">
          <section class="chat-group">
            <div class="chat-window" id="chat-window"></div>
            <form id="chat-form">
              <div class="input-group">
                <span id="write-message"><i class="fa-solid fa-ellipsis fa-beat fa-2xl"></i></span>
                <input class='text-bar' maxlength="500" type="text" id="message" placeholder="Digite sua mensagem">
                  <button class="emoji-button" type="button" onclick="openModal()">
                      <i class="fas fa-skull"></i>
                  </button>

                  <div class="modal-body" id="emojiModal">
                    <?php
                        foreach ($emojis as $emoji)
                        {
                          ?><button class='emoji-btn' type='button' data-emoji='<?=$emoji["character"]?>'><?=$emoji["character"]?></button><?php
                        }
                    ?>
                  </div>
                <button class='send-button' type="submit" onclick="sendMessage()"><i class="fa-solid fa-paper-plane"></i></button>
              </div>              
            </form>
          </section>
        </main>
      </section>
      <div class="scroll-down-area">
        <div class="scroll-down">
          <button class="scroll-button" onclick="scrollChat()"><i class="fa fa-chevron-down"></i></button>
        </div>
      </div>
    </div>
  </body>
  <script src="app/public/js/chat.js"></script>
  <script src="app/public/js/emojis.js"></script>
</html>